apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    # manifests === all dirs we want to sync
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild === random ID assigned to yoyur GCP Project (e.g. pacific-destiny-23123)
  googleCloudBuild:
    projectId: ticketing-dev-318410
    
  artifacts:
  # image === images produced from sync'd dir
    - image: us.gcr.io/ticketing-dev-318410/auth # used to be summertinio/auth -- but since we're on GCP, format is: us.gcr.io/[projectId]/[context (below)]
      context: auth # "auth" reflected in us.grc.io path in the line right above
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          # src === the set of files u want Skaffold to watch
          - src:  'src/**/*.ts'
            dest: . # where to put our files